<a href="https://colab.research.google.com/github/DilshanManathunge/TensorflowPractice/blob/master/Sequence/preparing_Time_Series_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf 
import numpy as np 
import matplotlib.pyplot as plt 

In [23]:
dataset = tf.data.Dataset.range(10)

In [24]:
dataset = dataset.window(5,shift=1)

In [25]:
for window in dataset:
  for val in window:
    print(val.numpy(),end=' ')
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


In [28]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,shift = 1 ,drop_remainder = True)
for window in dataset:
  for val in window:
    print(val.numpy(),end = " ")
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [33]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,shift = 1 ,drop_remainder = True)
dataset = dataset.flat_map(lambda window :window.batch(5))
for val in dataset:
  print(val.numpy())
  print()

[0 1 2 3 4]

[1 2 3 4 5]

[2 3 4 5 6]

[3 4 5 6 7]

[4 5 6 7 8]

[5 6 7 8 9]



In [35]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,shift = 1 ,drop_remainder = True)
dataset = dataset.flat_map(lambda window :window.batch(5))
dataset = dataset.map(lambda window : (window[:-1],window[-1:]))
for x,y in dataset:
  print(x.numpy(),y.numpy())
  print()

[0 1 2 3] [4]

[1 2 3 4] [5]

[2 3 4 5] [6]

[3 4 5 6] [7]

[4 5 6 7] [8]

[5 6 7 8] [9]



In [38]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,shift = 1 ,drop_remainder = True)
dataset = dataset.flat_map(lambda window : window.batch(5))
dataset = dataset.map(lambda window: (window[:-1],window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2).prefetch(1)

for x,y in dataset:
  print("x  = ",x.numpy())
  print("y  = ",y.numpy())

x  =  [[4 5 6 7]
 [0 1 2 3]]
y  =  [[8]
 [4]]
x  =  [[1 2 3 4]
 [3 4 5 6]]
y  =  [[5]
 [7]]
x  =  [[2 3 4 5]
 [5 6 7 8]]
y  =  [[6]
 [9]]
